/**
 * Benjamin Cash Delivery Service - Centralized Strings
 * 
 * Tone: Trustworthy, friendly, reliable — with a light dash of charm
 * Voice: Calm, confident, courteous
 * Style: Plain English, short sentences, hint of charm
 * 
 * Safety-first phrasing: Emphasize privacy & trust in every message
 */

export const strings = {
  // Shared buttons
  buttons: {
    confirm: "Confirm",
    cancel: "Cancel",
    continue: "Continue",
    back: "Go back",
    close: "Close",
    done: "Done",
    next: "Next",
    tryAgain: "Try again",
    ok: "Got it",
    accept: "Accept",
    decline: "Decline",
    complete: "Mark complete",
    start: "Start job",
    finish: "Finish job",
    withdraw: "Withdraw request",
    callSupport: "Contact support",
    viewDetails: "View details",
    loading: "Loading...",
    navigate: "Navigate",
  },

  // Shared CTAs
  cta: {
    primary: "Get Cash Delivered",
    secondary: "Track My Order",
    runnerStart: "Start Earning with Benjamin",
    runnerActive: "See Available Jobs",
    invite: "Invite a Friend",
  },

  // Shared status labels
  status: {
    pending: "Pending",
    accepted: "Runner Assigned",
    runnerAtATM: "At ATM",
    cashPicked: "Cash Collected",
    enRoute: "On the Way",
    pendingHandoff: "Ready for Handoff",
    delivered: "Delivered",
    completed: "Completed",
    canceled: "Canceled",
  },

  // Shared toast messages
  toasts: {
    orderPlaced: "Request received. Benjamin's on it.",
    orderAccepted: "A runner just picked up your order.",
    statusUpdated: "Order updated successfully.",
    orderDelivered: "Delivered safely — verified and done.",
    orderCanceled: "Order canceled.",
    otpVerified: "Delivery verified. Enjoy your cash.",
    otpGenerated: "Verification code generated and ready.",
    runnerAccepted: "Job accepted — on your way to the ATM.",
    runnerCompleted: "Delivery complete. Well done.",
    runnerAtATM: "Status updated — you're at the ATM.",
    cashWithdrawn: "Cash collected — heading to customer.",
    error: "Something went wrong — please try again.",
    avatarUploaded: "Profile photo updated successfully.",
    avatarRemoved: "Profile photo removed.",
    profileSaved: "Profile updated successfully.",
  },

  // Shared error messages
  errors: {
    generic: "Something went wrong. Please try again.",
    network: "Connection lost. Reconnecting…",
    unauthorized: "Session expired. Please sign in again.",
    location: "Location access needed to continue.",
    permission: "Permission denied. Check your settings.",
    orderNotFound: "Order not found.",
    invalidOTP: "Invalid or expired code.",
    uploadFailed: "Upload failed. Please try again.",
    fileTooLarge: "File too large. Maximum 5MB.",
    invalidFileType: "Invalid file type. Use JPG, PNG, or WebP.",
  },

  // Shared empty states
  emptyStates: {
    noOrders: "No active orders yet.",
    noOrdersDesc: "Your cash delivery orders will appear here once you make a request.",
    noJobs: "No available jobs right now — check back soon.",
    noJobsDesc: "New delivery requests will appear here as they come in.",
    noHistory: "No past deliveries yet.",
    noHistoryDesc: "Your completed orders will show up here.",
    loading: "Loading your data…",
  },

  // Customer-specific strings
  customer: {
    homeTitle: "Cash, delivered.",
    homeSubtitle: "Skip the ATM. Withdraw in minutes — right to your door.",
    newOrderTitle: "How much do you need?",
    newOrderSubtitle: "Enter your amount. We'll handle the rest.",
    newOrderButton: "New Request",
    trackingTitle: "Your Cash is on the Move",
    trackingDesc: "Once your runner collects the cash, you'll see their route live.",
    trackingBackButton: "Back to Orders",
    otpTitle: "Verify Delivery",
    otpPrompt: "Share this code with the runner to complete delivery",
    otpLabel: "Verification Code",
    successTitle: "All Set",
    successSubtitle: "Cash received. Thanks for trusting Benjamin.",
    canceledTitle: "Request Canceled",
    canceledSubtitle: "No charge applied. You can place another anytime.",
    cancelButton: "Cancel Order",
    cancelConfirm: "Are you sure you want to cancel this order?",
    supportNote: "Need help? We're here 24/7.",
    ordersTitle: "My Orders",
    ordersSubtitle: "View and track your cash delivery orders",
    orderHistoryTitle: "Order History",
    orderHistoryDesc: "All your cash delivery requests",
    createFirstOrder: "Create Your First Order",
    deliveryProgress: "Delivery Progress",
    deliveryProgressDesc: "Track your cash delivery in real-time",
    deliveryAddress: "Delivery Address",
    cashAmount: "Cash Amount",
    totalPayment: "Total Payment",
    runner: "Runner",
    orderDetails: "Order Details",
    feeBreakdown: "Fee Breakdown",
    platformFee: "Platform Fee",
    deliveryFee: "Delivery Fee",
    complianceFee: "Compliance Fee",
    runnerHidden: "Runner (hidden)",
    unknown: "Unknown",
    waitingForRunner: "Waiting for runner",
    runnerAccepted: "Runner accepted",
    runnerAtATM: "Runner at ATM",
    cashWithdrawn: "Cash withdrawn",
    deliveryComplete: "Delivery complete",
    orderCancelled: "Order was cancelled",
    addressRequired: "Please enter your delivery address",
    dailyLimitExceeded: "Daily limit exceeded. Available:",
    cashAmountTitle: "Cash Amount",
    cashAmountDesc: "Select amount between $100 - $1,000 (in $20 increments)",
    deliveryAddressLabel: "Delivery Address",
    deliveryAddressPlaceholder: "123 Main St, City, State",
    deliveryNotesLabel: "Delivery Notes (Optional)",
    deliveryNotesPlaceholder: "e.g., Ring doorbell, meet at lobby, call when arriving...",
    deliveryNotesHelp: "Provide any special instructions for the runner",
    feeBreakdownTitle: "Fee Breakdown",
    feeBreakdownDesc: "Transparent pricing breakdown",
    submitButton: "Request Cash Delivery",
    totalServiceFee: "Total Service Fee",
    dailyLimitInfo: "Your daily limit",
    usedToday: "Used today",
  },

  // Runner-specific strings
  runner: {
    dashboardTitle: "Available Jobs",
    dashboardSubtitle: "Pick a request and start your run.",
    jobCardPayout: "Payout",
    jobCardDistance: "Distance",
    jobCardAmount: "Amount",
    acceptJob: "Accept Job",
    collectingCash: "Collecting cash...",
    enRoute: "Heading to customer...",
    delivered: "Delivery confirmed",
    completed: "Job complete",
    noJobs: "No open jobs right now.",
    earningsTitle: "Earnings Summary",
    monthlyEarnings: "Monthly Earnings",
    activeJobTitle: "Active Delivery",
    confirmPickup: "Mark as Cash Picked",
    confirmDelivery: "Complete Delivery",
    safetyNote: "Runner identity and location shown only after cash is collected.",
    deliverySteps: "Delivery Steps",
    deliveryStepsDesc: "Follow these steps to complete the delivery",
    step1Title: "Step 1: Go to ATM",
    step1Desc: "Head to the nearest ATM to withdraw",
    step1Button: "I've Arrived at ATM",
    step2Title: "Step 2: Withdraw Cash",
    step2Desc: "Withdraw",
    step2Button: "Cash Withdrawn - Generate OTP",
    step3Title: "Step 3: Complete Delivery",
    step3Desc: "Meet the customer and ask for their 6-digit verification code",
    step3Button: "Verify & Complete Delivery",
    completedTitle: "Delivery Completed!",
    completedDesc: "You earned",
    cashToWithdraw: "Cash to Withdraw",
    yourEarnings: "Your Earnings",
    customer: "Customer",
    deliveryNotes: "Delivery Notes",
    deliveryProgress: "Delivery Progress",
    deliveryProgressDesc: "Track your delivery progress",
    ordersTitle: "My Orders",
    ordersSubtitle: "View your active and completed deliveries",
    backToOrders: "Back to Orders",
    enterOTP: "Enter Verification Code",
  },

  // Admin-specific strings
  admin: {
    monitorTitle: "Order Monitoring",
    monitorSubtitle: "Real-time monitoring of all cash delivery orders",
    drawerTitle: "Order Details",
    drawerTimeline: "Order Progress",
    drawerEvents: "Activity Log",
    drawerMap: "Route Overview",
    empty: "No active deliveries.",
    emptyDesc: "Orders will appear here once customers make requests",
    totalOrders: "Total Orders",
    pending: "Pending",
    inProgress: "In Progress",
    completed: "Completed",
    cancelled: "Cancelled",
    allOrders: "All Orders",
    allOrdersDesc: "Monitor and track all delivery orders",
    filterByStatus: "Filter by status",
    allStatuses: "All Statuses",
    orderId: "Order ID",
    amount: "Amount",
    total: "Total",
    created: "Created",
    actions: "Actions",
    clickToView: "Click to view",
    unassigned: "Unassigned",
    notAssigned: "Not assigned",
    orderInfo: "Order Information",
    customerInfo: "Customer Information",
    runnerInfo: "Runner Information",
    timeline: "Timeline",
    location: "Location",
    dashboardTitle: "Dashboard",
    dashboardSubtitle: "Overview of your cash delivery service",
    userManagementTitle: "User Management",
    userManagementSubtitle: "Manage customers, runners, and admins",
    invitationTitle: "Invitation Management",
    invitationSubtitle: "Send invitations to new runners and admins",
  },

  // Profile strings
  profile: {
    title: "Profile",
    subtitle: "Your details stay private and secure.",
    accountTitle: "Account",
    accountSubtitle: "Manage your profile and preferences",
    nameLabel: "Full name",
    firstNameLabel: "First name",
    lastNameLabel: "Last name",
    emailLabel: "Email",
    phoneLabel: "Phone number",
    avatarLabel: "Profile photo",
    uploadPhoto: "Change photo",
    removePhoto: "Remove photo",
    saveChanges: "Save changes",
    savedToast: "Profile updated successfully.",
    dragDropHint: "Drag & drop or click to upload",
    uploadButton: "Upload Avatar",
    removeButton: "Remove Avatar",
    personalInfo: "Personal Information",
    accountSettings: "Account Settings",
  },

  // Helper messages
  helpers: {
    safetyNotice: "For runner safety, photos and live locations are shown only after cash collection.",
    safetyBanner: "Runner photo and live location will be visible after cash pickup for your safety",
    deliveryTip: "Have your ID ready when receiving cash.",
    otpHelp: "If you didn't receive a code, contact support.",
    cashPickedNote: "Your runner just collected the cash. You'll now see live tracking.",
    refundInfo: "Canceled requests are refunded automatically.",
    appTagline: "Benjamin — Cash. Delivered. Securely.",
    mapBeforePickup: "Location details will be visible after cash pickup",
    mapAfterPickup: "Your runner is on the way",
    estimatedArrival: "Estimated arrival",
    runnerMapATM: "Navigate to ATM to collect cash",
    runnerMapCustomer: "Navigate to customer for delivery",
  },

  // App branding
  branding: {
    appName: "Benjamin",
    tagline: "Cash, delivered.",
    fullTagline: "Cash. Delivered. Securely.",
    signature: "Benjamin's on it.",
    safeSimpleHuman: "Safe, simple, human.",
  },
};

export default strings;
